### PR TITLE
Sound Issue Fixed

### PR DESCRIPTION
**Pull request by Adedoyin-Emmanuel**
### Fixed Sound Issue
Apparently, you were getting the `Howler` issue because you didn't install the `@types` definition. I did that but I had an issue with it, since **Howler** wasn't built to support react. I couldn't dynamically change the props value. So I had to switch back to default **HTML** audio tags which works very very fine.

### Update Summary
- Fixed sound issue
- Added background game sound
- Added randomized game sounds :1st_place_medal: 
- Removed Howler from `package.json`

### CODE REVIEW

**Comment by youngancient** [comment]
Hi @Adedoyin-Emmanuel nice work. Please check your PR, the redux side seems you deleted something, vercel pointed out a deployment error. The error is in the dataSlice file.
pr

**Comment by Adedoyin-Emmanuel** [comment]
@youngancient  Please review my pull request

**Comment by youngancient** [comment]
Hey @Adedoyin-Emmanuel Really nice. 
The errors are gone now. So I tested it and it works well but when the user picks the wrong question, it doesn't make any sound. It only makes a sound when the user picks the correct question. Is this correct or it's a logical bug?

**Comment by Adedoyin-Emmanuel** [comment]
@youngancient Yeah it is correct, though I didn't add that because there aren't any wrong or fail sound, I would find one and

**Comment by Adedoyin-Emmanuel** [comment]
@youngancient All issues fixed, hopefully it should work now

**Comment by youngancient** [comment]
@Adedoyin-Emmanuel there were no bugs now😪
I have two deployment versions, you can test them here:
former: https://techiequiz-1nvjawa7p-youngancient.vercel.app/
present (after current commit) : https://techiequiz-1qe37b19i-youngancient.vercel.app/
did you notice any difference between the two?
The former loads faster than the present, and the sound when the user gets a question correctly comes immediately the user picks the option which is wrong. The former was perfect, it only required you to add an extra sound.
Tbh I would have merged the first but I just wanted you to add sound when the user fails a question and now I don't know again 😥

**Comment by Adedoyin-Emmanuel** [comment]
Oh okay,  The issue I actually changed that, I was thinking the correct time takes time before playing,  I would fix that up and try again,  as for the website loading speed,  I think it is because of the sounds added and the Page trying to load the sound before playing it,  I would look into it and hopefully it should work this time 👍

**Comment by youngancient** [comment]
If you could revert to the former commit or fix what broke.
There is an issue with the ending sound. When the result screen shows, the sounds starts playing but it should stop the moment the user clicks try again, but now it doesn't. It plays the the sound ends.

**Comment by Adedoyin-Emmanuel** [comment]
@youngancient Check the recent deployment, I works fine now

**Comment by youngancient** [comment]
@Adedoyin-Emmanuel  I merged the PR and I don't know why the audio isn't playing at all when i visit the main URL: https://techiequiz.vercel.app/
any ideas?

**Pull request merged**
